enyo.depends(
  "source/biblez.js",
  "source/biblezPopup.js",
  "source/biblezScroller.js",
  "source/biblezModuleManager.js",
  "source/biblezTools.js",
  "source/mapping.js",
  "css/biblez.css"
);
