var languages = {
    "af": "Afrikaans", 
    "am": "Amharic",
    "ang": "Old English (ca. 450-1100)",
    "ar": "Arabic", 
    "as": "Assamese", 
    "az": "Azerbaijani",
    "azb": "South Azerbaijani",
    "bal": "Balochi",
    "bar": "Bavarian",
    "be": "Belarusian", 
    "bg": "Bulgarian", 
    "bn": "Bengali", 
    "bn_IN": "Bengali (India)",
    "br": "Breton",
    "bs": "Bosnian", 
    "ca@valencia": "Catalan (Valencian)",
    "ch": "Chamorro",
    "chr": "Cherokee",
    "ckb": "Central Kurdish",
    "cs": "Czech", 
    "cy": "Welsh", 
    "da": "Danish", 
    "de": "German", 
    "de_CH": "Swiss German", 
    "dz": "Dzongkha",
    "el": "Greek", 
    "en": "English", 
    "en_GB": "English (United Kingdom)", 
    "en_ZA": "English (South Africa)",
    "enm": "Middle English (1100-1500)",
    "es": "Spanish (Castilian)", 
    "et": "Estonian", 
    "eu": "Basque", 
    "fa": "Persian", 
    "fi": "Finnish", 
    "fr": "French", 
    "fur": "Friulian", 
    "fy": "Western Frisian", 
    "ga": "Irish", 
    "gl": "Galician",
    "got": "Gothic",
    "grc": "Ancient Greek (to 1453)",
    "gu": "Gujarati",
    "gv": "Manx",
    "haw": "Hawaiian",
    "he": "Hebrew", 
    "hi": "Hindi", 
    "hr": "Croatian", 
    "ht": "Haitian (Haitian Creole)", 
    "hu": "Hungarian", 
    "hy": "Armenian", 
    "id": "Indonesian", 
    "ilo": "Iloko", 
    "is": "Icelandic", 
    "it": "Italian",
    "itz": "Itzá",
    "ja": "Japanese", 
    "ka": "Georgian",
    "kek": "Kekchí",
    "kn": "Kannada", 
    "ko": "Korean", 
    "ku": "Kurdish", 
    "lo": "Lao", 
    "lt": "Lithuanian", 
    "lv": "Latvian", 
    "mai": "Maithili", 
    "mk": "Macedonian", 
    "ml": "Malayalam", 
    "mn": "Mongolian", 
    "mr": "Marathi", 
    "ms": "Malay", 
    "mt": "Maltese", 
    "my": "Burmese", 
    "nb": "Norwegian Bokm\u00e5l",
    "nd": "North Ndebele",
    "ne": "Nepali", 
    "nl": "Dutch (Netherlands)", 
    "nn": "Norwegian Nynorsk", 
    "no": "Norwegian", 
    "nso": "Northern Sotho", 
    "or": "Oriya", 
    "pa": "Panjabi (Punjabi)", 
    "pl": "Polish",
    "pot": "Potawatomi",
    "ppk": "Uma",
    "pt": "Portuguese", 
    "pt_BR": "Portuguese (Brazilian)",
    "rmk": "Caló",
    "ro": "Romanian", 
    "ru": "Russian", 
    "si": "Sinhala", 
    "sk": "Slovak", 
    "sl": "Slovenian",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian", 
    "sr": "Serbian",
    "sr@latin": "Serbian (Latin)",
    "srn": "Sranan Tongo",
    "st": "Sotho, Southern", 
    "sv": "Swedish",
    "syr": "Syriac",
    "ta": "Tamil", 
    "te": "Telugu", 
    "tg": "Tajik", 
    "th": "Thai", 
    "tl": "Tagalog",
    "tlh": "Klingon",
    "tn": "Tswana",
    "tr": "Turkish",
    "ty": "Tahitian",
    "ur": "Urdu",
    "ury": "Orya",
    "uk": "Ukrainian", 
    "vi": "Vietnamese", 
    "wo": "Wolof",
    "zh": "Chinese",
    "zh_CN": "Chinese (China)", 
    "zh_HK": "Chinese (Hong Kong)", 
    "zh_TW": "Chinese (Taiwan)", 
    "zu": "Zulu", 
    "es_AR": "Spanish (Argentinian)", 
    "bo": "Tibetan", 
    "ast": "Asturian", 
    "en_US": "English (United States)", 
    "eo": "Esperanto", 
    "ks": "Kashmiri", 
    "ky": "Kirgyz", 
    "la": "Latin", 
    "xh": "Xhosa", 
    "es_MX": "Spanish (Mexican)", 
    "km": "Khmer", 
    "fo": "Faroese", 
    "kk": "Kazakh", 
    "nl_BE": "Dutch (Belgium/Flemish)", 
    "ca": "Catalan", 
    "tk": "Turkmen", 
    "uz": "Uzbek", 
    "bn_BD": "Bengali (Bangladesh)", 
    "sw": "Swahili", 
    "sco": "Scots", 
    "lb": "Luxembourgish", 
    "ln": "Lingala", 
    "tt": "Tatar", 
    "fil": "Filipino", 
    "gun": "Gun", 
    "pms": "Piemontese", 
    "arn": "Mapudungun", 
    "rm": "Romansh", 
    "wa": "Walloon", 
    "jv": "Javanese", 
    "oc": "Occitan (post 1500)", 
    "ps": "Pushto", 
    "ha": "Hausa", 
    "mg": "Malagasy", 
    "mi": "Maori", 
    "ug": "Uighur", 
    "ak": "Akan", 
    "an": "Aragonese", 
    "su": "Sundanese", 
    "pap": "Papiamento", 
    "nah": "Nahuatl", 
    "csb": "Kashubian", 
    "nap": "Neapolitan", 
    "kw": "Cornish", 
    "ve": "Venda", 
    "son": "Songhay", 
    "en_CA": " English (Canada)", 
    "rw": "Kinyarwanda", 
    "crh": "Crimean Turkish", 
    "li": "Limburgian", 
    "es_VE": "Spanish (Venezuela)", 
    "frp": "Franco-Proven\u00e7al (Arpitan)", 
    "yi": "Yiddish", 
    "es_ES": "Spanish (Spain)", 
    "fr_FR": "French (France)", 
    "de_DE": "German (Germany)", 
    "yo": "Yoruba", 
    "ig": "Igbo", 
    "es_PR": "Spanish (Puerto Rico)", 
    "nds": "Low German", 
    "nr": "Ndebele, South", 
    "gd": "Gaelic, Scottish", 
    "es_CL": "Spanish (Chile)", 
    "en_IE": "English (Ireland)", 
    "ta_LK": "Tamil (Sri-Lanka)", 
    "se": "Northern Sami", 
    "hsb": "Upper Sorbian", 
    "hne": "Chhattisgarhi", 
    "en_AU": "English (Australia)", 
    "fr_CA": "French (Canada)", 
    "ia": "Interlingua"
};

var mappings = {
    "texts" : $L("Biblical Texts"),
    "lexdict" : $L("Lexicons / Dictionaries"),
    "genbook" : $L("Generic Books"),
    "comments" : $L("Commentaries")
};